local addonname, aegerUI = ...

function aegerUI:InstallHandyNotes()
	if not IsAddOnLoaded("HandyNotes") then return end
	
		_G.aegerUI_HandyNotes_Install = {
		["AhnQirajTheFallenKingdom"] = {
			[46570731] = {
				["icon"] = 28,
				["title"] = "Temple of Ahn'Qiraj 40",
				["desc"] = "Entrance",
			},
			[59091404] = {
				["title"] = " Temple of Ahn'Qiraj 20",
				["icon"] = 28,
				["desc"] = "Entrance",
			},
		},
		["Barrens"] = {
			[40182001] = {
				["icon"] = 15,
				["level"] = 1,
				["title"] = "Repair",
				["desc"] = "",
			},
			[48155658] = {
				["icon"] = 15,
				["level"] = 1,
				["title"] = "Repair",
				["desc"] = "",
			},
			[49105748] = {
				["icon"] = 16,
				["level"] = 1,
				["title"] = "Stable Master",
				["desc"] = "",
			},
			[50175903] = {
				["icon"] = 21,
				["level"] = 1,
				["title"] = "Baker",
				["desc"] = "",
			},
			[68497129] = {
				["icon"] = 10,
				["level"] = 1,
				["title"] = "Bank",
				["desc"] = "",
			},
			[38986945] = {
				["icon"] = 3,
				["level"] = 1,
				["title"] = "Wailing Caverns Entrance",
				["desc"] = "",
			},
			[67617157] = {
				["icon"] = 21,
				["level"] = 1,
				["title"] = "Food/Drink",
				["desc"] = "",
			},
			[48525843] = {
				["icon"] = 23,
				["level"] = 1,
				["title"] = "Reagents",
				["desc"] = "",
			},
			[55116176] = {
				["icon"] = 21,
				["level"] = 1,
				["title"] = "Baker",
				["desc"] = "",
			},
			[40311981] = {
				["icon"] = 21,
				["level"] = 1,
				["title"] = "Smokeywood Pastures",
				["desc"] = "",
			},
			[55376122] = {
				["icon"] = 18,
				["level"] = 1,
				["title"] = "Cooking Trainer",
				["desc"] = "",
			},
			[70067324] = {
				["icon"] = 28,
				["level"] = 1,
				["title"] = "Ship to STV",
				["desc"] = "",
			},
			[62971727] = {
				["icon"] = 21,
				["level"] = 1,
				["title"] = "General Goods",
				["desc"] = "",
			},
			[62711684] = {
				["icon"] = 15,
				["level"] = 1,
				["title"] = "Repair",
				["desc"] = "",
			},
			[62381692] = {
				["icon"] = 16,
				["level"] = 1,
				["title"] = "Stable Master",
				["desc"] = "",
			},
			[42451500] = {
				["icon"] = 15,
				["level"] = 1,
				["title"] = "Repair",
				["desc"] = "",
			},
			[67507268] = {
				["icon"] = 15,
				["level"] = 1,
				["title"] = "Repair",
				["desc"] = "",
			},
			[67537425] = {
				["icon"] = 16,
				["level"] = 1,
				["title"] = "Stable Master",
				["desc"] = "",
			},
			[39982026] = {
				["icon"] = 25,
				["level"] = 1,
				["title"] = "Warsong Gulch Entrance",
				["desc"] = "",
			},
			[49685887] = {
				["icon"] = 14,
				["level"] = 1,
				["title"] = "Mailbox",
				["desc"] = "",
			},
		},
		["DragonSoul"] = {
			[35215821] = {
				["title"] = "Warlord Zon'ozz",
				["level"] = 1,
				["icon"] = 8,
				["desc"] = "",
			},
			[70505949] = {
				["title"] = "Yor'sahj the Unsleeping",
				["level"] = 1,
				["icon"] = 8,
				["desc"] = "",
			},
		},
		["TheStormPeaks"] = {
			[41767868] = {
				["title"] = "Val'kyr Pet",
				["icon"] = 4,
				["desc"] = "",
			},
			[65604227] = {
				["title"] = "Val'kyr Pet",
				["icon"] = 4,
				["desc"] = "",
			},
			[28935093] = {
				["title"] = "Val'kyr Pet",
				["icon"] = 4,
				["desc"] = "",
			},
		},
		["Hyjal"] = {
			[61323281] = {
				["icon"] = 16,
				["title"] = "Brok",
				["desc"] = "Pet-Trainer\nWildlife, Magic, Critter",
			},
		},
		["ThuntheKingLootRoom"] = {
			[35141777] = {
				["icon"] = 9,
				["title"] = "Golden Box",
				["desc"] = "",
			},
			[44461913] = {
				["icon"] = 9,
				["title"] = "Golden Box",
				["desc"] = "",
			},
			[40891362] = {
				["icon"] = 9,
				["title"] = "Golden Box",
				["desc"] = "",
			},
			[29234796] = {
				["icon"] = 9,
				["title"] = "Golden Box",
				["desc"] = "",
			},
			[25032408] = {
				["icon"] = 9,
				["title"] = "Golden Box",
				["desc"] = "",
			},
			[40682304] = {
				["icon"] = 9,
				["title"] = "Golden Box",
				["desc"] = "",
			},
			[26205282] = {
				["icon"] = 9,
				["title"] = "Golden Box",
				["desc"] = "",
			},
			[47181530] = {
				["icon"] = 9,
				["title"] = "Golden Box",
				["desc"] = "",
			},
			[29714915] = {
				["icon"] = 9,
				["title"] = "Golden Box",
				["desc"] = "",
			},
			[25032249] = {
				["icon"] = 9,
				["title"] = "Golden Box",
				["desc"] = "",
			},
			[27705011] = {
				["icon"] = 9,
				["title"] = "Golden Box",
				["desc"] = "",
			},
			[29192600] = {
				["icon"] = 9,
				["title"] = "Golden Box",
				["desc"] = "",
			},
			[53931378] = {
				["icon"] = 9,
				["title"] = "Golden Box",
				["desc"] = "",
			},
			[29455019] = {
				["icon"] = 9,
				["title"] = "Golden Box",
				["desc"] = "",
			},
			[27485961] = {
				["title"] = "Start",
				["icon"] = 19,
				["desc"] = "",
			},
			[36052025] = {
				["icon"] = 9,
				["title"] = "Golden Box",
				["desc"] = "",
			},
			[42382504] = {
				["icon"] = 9,
				["title"] = "Golden Box",
				["desc"] = "",
			},
			[28124117] = {
				["icon"] = 9,
				["title"] = "Golden Box",
				["desc"] = "",
			},
			[52121107] = {
				["icon"] = 7,
				["title"] = "Tenwu of the Red Smoke",
				["desc"] = "",
			},
			[54151825] = {
				["icon"] = 9,
				["title"] = "Golden Box",
				["desc"] = "",
			},
			[29711554] = {
				["icon"] = 9,
				["title"] = "Golden Box",
				["desc"] = "",
			},
			[31471538] = {
				["icon"] = 9,
				["title"] = "Golden Box",
				["desc"] = "",
			},
			[26793199] = {
				["icon"] = 9,
				["title"] = "Golden Box",
				["desc"] = "",
			},
			[27211993] = {
				["icon"] = 9,
				["title"] = "Golden Box",
				["desc"] = "",
			},
			[29334626] = {
				["icon"] = 9,
				["title"] = "Golden Box",
				["desc"] = "",
			},
			[25671817] = {
				["icon"] = 9,
				["title"] = "Golden Box",
				["desc"] = "",
			},
			[51382783] = {
				["icon"] = 9,
				["title"] = "Golden Box",
				["desc"] = "",
			},
			[29084005] = {
				["icon"] = 9,
				["title"] = "Golden Box",
				["desc"] = "",
			},
			[28283191] = {
				["icon"] = 9,
				["title"] = "Golden Box",
				["desc"] = "",
			},
			[26045554] = {
				["icon"] = 9,
				["title"] = "Golden Box",
				["desc"] = "",
			},
			[26253622] = {
				["title"] = "Switch",
				["icon"] = 20,
				["desc"] = "",
			},
			[54201969] = {
				["icon"] = 9,
				["title"] = "Golden Box",
				["desc"] = "",
			},
			[32801610] = {
				["title"] = "Switch",
				["icon"] = 20,
				["desc"] = "",
			},
			[44191290] = {
				["title"] = "Switch",
				["icon"] = 20,
				["desc"] = "",
			},
			[53241905] = {
				["icon"] = 8,
				["title"] = "God-Hulk Gulkan (Boss)",
				["desc"] = "",
			},
		},
		["BlackwingLair"] = {
			[41626086] = {
				["title"] = "Boss",
				["level"] = 1,
				["icon"] = 8,
				["desc"] = "",
			},
			[39277216] = {
				["title"] = "Chromaggus",
				["level"] = 4,
				["icon"] = 8,
				["desc"] = "Pet: Chrominius",
			},
			[50186188] = {
				["icon"] = 8,
				["level"] = 3,
				["title"] = "Broodlord Lashlayer",
				["desc"] = "",
			},
		},
		["Deepholm"] = {
			[49675735] = {
				["icon"] = 16,
				["title"] = "Bordin Steadyfist",
				["desc"] = "Pet-Trainer\nElemental, Critter, Elemental",
			},
		},
		["AhnQiraj"] = {
			[34354458] = {
				["title"] = "Transition to C'Thun",
				["level"] = 1,
				["icon"] = 8,
				["desc"] = "",
			},
		},
		["Krasarang"] = {
			[53463861] = {
				["icon"] = 1,
				["title"] = "Gaarn the Toxic",
				["desc"] = "",
			},
			[50698883] = {
				["icon"] = 8,
				["title"] = "Spriggin",
				["desc"] = "Rare Mob",
			},
			[54523240] = {
				["icon"] = 8,
				["title"] = "Gaarn the Toxic",
				["desc"] = "Rare Mob",
			},
			[28753762] = {
				["icon"] = 8,
				["title"] = "Cournith Waterstrider",
				["desc"] = "Rare Mob\nin the temple",
			},
			[39555434] = {
				["icon"] = 8,
				["title"] = "Ruun Ghostpaw",
				["desc"] = "Rare Mob Panda\nIn the building top floor",
			},
			[51568996] = {
				["title"] = "Recipe: Banana Infused Rum",
				["icon"] = 4,
				["desc"] = "Up on the ship in a barrel",
			},
			[39022848] = {
				["icon"] = 8,
				["title"] = "Go-Kan",
				["desc"] = "Rare Mob",
			},
			[56574800] = {
				["icon"] = 8,
				["title"] = "Arness the Scale",
				["desc"] = "Rare Mob",
			},
			[13943527] = {
				["icon"] = 8,
				["title"] = "Torik-Ethis",
				["desc"] = "Rare Mob",
			},
			[41589133] = {
				["title"] = "Equipment Locker",
				["icon"] = 4,
				["desc"] = "= Random BoP Boots 419 lvl 86\nvery bottom of ship",
			},
			[66892142] = {
				["icon"] = 8,
				["title"] = "Qu'nas",
				["desc"] = "Rare Mob",
			},
			[68464389] = {
				["icon"] = 6,
				["title"] = "Dailys",
				["desc"] = "Angler Quests",
			},
			[49964881] = {
				["title"] = "Pandaren Fishing Spear",
				["icon"] = 4,
				["desc"] = "= Agility Polearm 419 lvl 86\nStuck in the ground behind Uncle Deming",
			},
		},
		["MoltenCore"] = {
			[82588315] = {
				["title"] = "Sulfuron Harbinger",
				["icon"] = 8,
				["desc"] = "Pet: Mark of Flame",
			},
			[68255861] = {
				["title"] = "Golemagg the Incinerator",
				["icon"] = 8,
				["desc"] = "Pet: Core of Hardened Ash",
			},
			[69212405] = {
				["icon"] = 1,
				["level"] = 5,
				["title"] = "Corefire inp",
				["desc"] = "",
			},
			[68462469] = {
				["icon"] = 8,
				["level"] = 5,
				["title"] = "Magmadar",
				["desc"] = "Pet: Corefire inp",
			},
			[68782349] = {
				["title"] = "Magmadar",
				["icon"] = 8,
				["desc"] = "Pet: Corefire inp",
			},
		},
		["Dalaran"] = {
			[53191688] = {
				["icon"] = 10,
				["level"] = 1,
				["title"] = "Bank",
				["desc"] = "",
			},
			[35382866] = {
				["icon"] = 18,
				["level"] = 1,
				["title"] = "Leatherworker",
				["desc"] = "",
			},
			[39134066] = {
				["icon"] = 18,
				["level"] = 1,
				["title"] = "Enchanting",
				["desc"] = "",
			},
			[43213413] = {
				["icon"] = 18,
				["level"] = 1,
				["title"] = "Herbalism",
				["desc"] = "",
			},
			[36753708] = {
				["icon"] = 18,
				["level"] = 1,
				["title"] = "First Aid",
				["desc"] = "",
			},
			[40323473] = {
				["icon"] = 18,
				["level"] = 1,
				["title"] = "Jewlcrafter",
				["desc"] = "",
			},
			[41783679] = {
				["icon"] = 18,
				["level"] = 1,
				["title"] = "Inscription",
				["desc"] = "",
			},
			[45572844] = {
				["icon"] = 18,
				["level"] = 1,
				["title"] = "Blacksmith",
				["desc"] = "",
			},
			[39232543] = {
				["icon"] = 18,
				["level"] = 1,
				["title"] = "Engineering",
				["desc"] = "",
			},
			[43362658] = {
				["icon"] = 18,
				["level"] = 1,
				["title"] = "Enchanted Anvil",
				["desc"] = "",
			},
			[41202540] = {
				["icon"] = 18,
				["level"] = 1,
				["title"] = "Miners",
				["desc"] = "",
			},
			[43897697] = {
				["icon"] = 10,
				["level"] = 1,
				["title"] = "Bank",
				["desc"] = "",
			},
			[42243208] = {
				["icon"] = 18,
				["level"] = 1,
				["title"] = "Alchemy",
				["desc"] = "",
			},
			[36093407] = {
				["icon"] = 18,
				["level"] = 1,
				["title"] = "Tailoring",
				["desc"] = "",
			},
		},
		["SilvermoonCity"] = {
			[68022916] = {
				["icon"] = 14,
				["level"] = 1,
				["title"] = "Mailbox",
				["desc"] = "",
			},
			[91895825] = {
				["icon"] = 9,
				["level"] = 1,
				["title"] = "Auction House",
				["desc"] = "",
			},
			[86203551] = {
				["icon"] = 15,
				["level"] = 1,
				["title"] = "Repair",
				["desc"] = "",
			},
			[81065834] = {
				["icon"] = 13,
				["level"] = 1,
				["title"] = "innkeeper",
				["desc"] = "",
			},
			[66777791] = {
				["icon"] = 10,
				["level"] = 1,
				["title"] = "Bank",
				["desc"] = "",
			},
			[88005097] = {
				["icon"] = 14,
				["level"] = 1,
				["title"] = "Mailbox",
				["desc"] = "",
			},
			[61396273] = {
				["icon"] = 9,
				["level"] = 1,
				["title"] = "Auction House",
				["desc"] = "",
			},
			[82693080] = {
				["icon"] = 16,
				["level"] = 1,
				["title"] = "Stable Master",
				["desc"] = "",
			},
			[49481466] = {
				["icon"] = 28,
				["level"] = 1,
				["title"] = "translocate to Undercity",
				["desc"] = "",
			},
			[58422100] = {
				["icon"] = 28,
				["level"] = 1,
				["title"] = "Portal to Blasted Lands",
				["desc"] = "",
			},
		},
		["ThunderBluff"] = {
			[46615867] = {
				["icon"] = 10,
				["level"] = 1,
				["title"] = "Bank",
				["desc"] = "",
			},
			[15972561] = {
				["icon"] = 3,
				["level"] = 1,
				["title"] = "Zeppelin to Ogrimir",
				["desc"] = "",
			},
			[40245180] = {
				["icon"] = 9,
				["level"] = 1,
				["title"] = "Auction House",
				["desc"] = "",
			},
			[23111363] = {
				["icon"] = 28,
				["level"] = 1,
				["title"] = "Portal to Blasted Lands",
				["desc"] = "",
			},
		},
		["ValleyofTrialsStart"] = {
			[42016674] = {
				["icon"] = 14,
				["level"] = 1,
				["title"] = "Mailbox",
				["desc"] = "",
			},
			[43366577] = {
				["icon"] = 15,
				["level"] = 1,
				["title"] = "Repair",
				["desc"] = "",
			},
			[42796241] = {
				["icon"] = 21,
				["level"] = 1,
				["title"] = "butcher",
				["desc"] = "",
			},
		},
		["ShattrathCity"] = {
			[59126053] = {
				["icon"] = 10,
				["level"] = 1,
				["title"] = "Scryer Bank",
				["desc"] = "",
			},
			[48712867] = {
				["icon"] = 10,
				["level"] = 1,
				["title"] = "Aldor Bank",
				["desc"] = "",
			},
		},
		["ShrineofTwoMoons"] = {
			[57054789] = {
				["title"] = "Repair",
				["level"] = 1,
				["icon"] = 15,
				["desc"] = "",
			},
			[22335309] = {
				["icon"] = 2,
				["level"] = 1,
				["title"] = "To Bank",
				["desc"] = "",
			},
			[77714156] = {
				["icon"] = 2,
				["level"] = 1,
				["title"] = "To Portals",
				["desc"] = "",
			},
		},
		["KunLaiSummit"] = {
			[35847350] = {
				["title"] = "Courageous Yon <Grand Master Pet Tamer>",
				["icon"] = 16,
				["desc"] = "Pet-Trainer (in the Cave 35.8, 73.6)\nWildlife, Flying, Critter",
			},
			[64281332] = {
				["icon"] = 8,
				["title"] = "Nessos the Oracle",
				["desc"] = "Rare Mob",
			},
			[45296270] = {
				["icon"] = 8,
				["title"] = "Scritch",
				["desc"] = "Rare Mob\nDrops +1000 reputation item",
			},
			[56847603] = {
				["icon"] = 4,
				["title"] = "Terracotta Head",
				["desc"] = "100g 28300xp\nCounts as treasure",
			},
			[50848638] = {
				["title"] = "Sha of Wrath (Worldboss)",
				["icon"] = 7,
				["desc"] = "",
			},
			[64649375] = {
				["title"] = "Thundering Pandaren Spirit <Grand Master Pet Tamer>",
				["cont"] = 1,
				["icon"] = 16,
				["desc"] = "Pet-Trainer\nCritter, Elemental, Wildlife",
			},
			[70996256] = {
				["title"] = "Sturdy Yaungol Spear",
				["icon"] = 4,
				["desc"] = "= Strength Spear 419 lvl 86\nOn a spawned weapon rack",
			},
			[38167863] = {
				["icon"] = 4,
				["title"] = "Kafa Press",
				["desc"] = "= 4000 Haste potion 10 min cd\nIn the cave 35.2, 76.3\nFrozen Trail Packer\nNPC-Scan: 64227",
			},
			[66727733] = {
				["title"] = "Sha of Wrath (Worldboss)",
				["icon"] = 7,
				["desc"] = "Spawns every 15-30 min igentwo in Kun-Lai\nKill Check Macro:\n/run for k, v in pairs({ Galleon=32098, Sha=32099, Nalak=32518, Oon=32519, Champ=32641, Key=32626, Barrens=32862}) do print(format(\"%s: %s\", k, IsQuestFlaggedCompleted(v) and \"\\124cff00ff00Yes\" or \"\\124cffff0000No\"))",
			},
			[71973417] = {
				["title"] = "Statue of Xuen",
				["icon"] = 4,
				["desc"] = "100g Grey Item 500k XP\nUnder water at 72.0, 34.0\nCounts as treasure",
			},
			[57667838] = {
				["title"] = "Havak",
				["icon"] = 8,
				["desc"] = "Rare Mob",
			},
			[37638073] = {
				["icon"] = 8,
				["title"] = "Ski'thik",
				["desc"] = "Rare Mob",
			},
			[75176722] = {
				["title"] = "Zandalari Warbringer & Warscout",
				["cont"] = 1,
				["icon"] = 8,
				["desc"] = "5.2 Rare Mob - Drops Mount\nJade, Slate, Amber, or Golden Primordial Direhorn\nNPC-Scan id: 69769 & 69768",
			},
			[50156176] = {
				["title"] = "Hozen Treasure Cache",
				["icon"] = 4,
				["desc"] = "Contains 100g + 177k XP\nCave Entrance: 50.4, 61.7\nAt the end of the cave: 49.4, 59.4",
			},
			[40424180] = {
				["icon"] = 8,
				["title"] = "Ahone the Wanderer",
				["desc"] = "Rare Mob",
			},
			[53207111] = {
				["title"] = "Hozen Warrior Spear",
				["icon"] = 4,
				["desc"] = "= Agi Polearm 434 lvl 86\nStuck in the stone in the cave at 24,6 65,3",
			},
			[64104554] = {
				["title"] = "Ancient Mogu Tablet",
				["icon"] = 4,
				["desc"] = "95g Grey Item 280k XP\nCaveEntrance: 63.9, 49.8\nIn the cave 64.2,45.2",
			},
			[69815083] = {
				["icon"] = 6,
				["title"] = "Dailys",
				["desc"] = "Golden Lotus:\nThe Celestials Exalted",
			},
			[53658073] = {
				["title"] = "Korda Torros",
				["icon"] = 8,
				["desc"] = "Rare Mob\n11% Foragers Gloves\n(Mining, Skinning, herbs)",
			},
			[44675235] = {
				["title"] = "Tablet of Ren Yun",
				["icon"] = 4,
				["desc"] = "Teaches Four Senses Brew\nUp on the hill next to the statue 44.7 52.4\nCounts as treasure!",
			},
			[52335081] = {
				["title"] = "Rikktik's Tiny Chest",
				["icon"] = 4,
				["desc"] = "105g Grey Item +51g + 200k XP\n(Rikktik's Tick Remover)\nIn the cave next to the monkey statue 52.6, 51.5\nCounts as treasure",
			},
			[48858055] = {
				["title"] = "Korda Torros",
				["icon"] = 1,
				["desc"] = "Rare Mob Spawn 2",
			},
			[59685259] = {
				["title"] = "Stolen Sprite Treasure",
				["icon"] = 4,
				["desc"] = "Contains 104g + 283k XP\nCaveEntrance: 59.5, 52.9 \nItem: 41.0, 42.7\nCounts as treasure!\n2 Various treasures are here in the cave",
			},
			[73517707] = {
				["icon"] = 8,
				["title"] = "Zai the Outcast",
				["desc"] = "Rare Mob",
			},
			[59613906] = {
				["icon"] = 28,
				["title"] = "Mogu'shan Vaults",
				["desc"] = "Entrance 10/25 Raid",
			},
			[54696714] = {
				["icon"] = 7,
				["title"] = "Sha of Wrath (Worldboss)",
				["desc"] = "Spawns every 15-30 min igentwo in Kun-Lai\n\nKill Check Macro:\n/run for k, v in pairs({ Galleon = 32098, Sha = 32099, Nalak = 32518}) do print(format(\"%s: %s\", k, IsQuestFlaggedCompleted(v) and \"Yes killed\" or \"No\")) end",
			},
			[37064779] = {
				["title"] = "Shado-Pan Monastery",
				["icon"] = 28,
				["desc"] = "Instance Entrance (87-89 / 90 Heroic)",
			},
			[55344530] = {
				["icon"] = 8,
				["title"] = "Borginn Darkfist",
				["desc"] = "Rare Mob",
			},
			[74517328] = {
				["title"] = "Sprite's Cloth Chest",
				["icon"] = 4,
				["desc"] = "= Random 86 BoP Cloak\nSmall box in the cave at the back",
			},
			[41736999] = {
				["icon"] = 6,
				["title"] = "Daily",
				["desc"] = "Is only Gold",
			},
		},
		["VashjirRuins"] = {
			[58128221] = {
				["title"] = "Poseidus",
				["icon"] = 8,
				["desc"] = "",
			},
			[46255045] = {
				["title"] = "Poseidus",
				["icon"] = 8,
				["desc"] = "",
			},
			[66144307] = {
				["title"] = "Poseidus",
				["icon"] = 8,
				["desc"] = "",
			},
			[39306810] = {
				["title"] = "Poseidus",
				["icon"] = 8,
				["desc"] = "",
			},
		},
		["CoilfangReservoir"] = {
			[59682613] = {
				["title"] = "Morgrin",
				["icon"] = 8,
				["desc"] = "",
			},
		},
		["Uldum_terrain1"] = {
			[56724163] = {
				["icon"] = 16,
				["title"] = "Obalis",
				["desc"] = "Pet-Trainer\nWildlife, Critter, Flying",
			},
			[46363441] = {
				["title"] = "Scourer of the Eternal Sands",
				["icon"] = 8,
				["desc"] = "64.6 30.4\nNPC-Scan: 50409",
			},
		},
		["CrystalsongForest"] = {
			[17055670] = {
				["title"] = "Val'kyr Pet",
				["icon"] = 4,
				["desc"] = "",
			},
			[66885062] = {
				["title"] = "Val'kyr Pet",
				["icon"] = 4,
				["desc"] = "",
			},
			[50005912] = {
				["icon"] = 16,
				["title"] = "Nearly Headless Jacob",
				["desc"] = "Pet-Trainer\nUndead, Undead, Undead",
			},
			[43574420] = {
				["title"] = "Val'kyr Pet",
				["icon"] = 4,
				["desc"] = "",
			},
		},
		["BoreanTundra"] = {
			[48170795] = {
				["icon"] = 4,
				["title"] = "Val'kyr Pet",
				["desc"] = "",
			},
			[32565960] = {
				["icon"] = 4,
				["title"] = "Val'kyr Pet",
				["desc"] = "",
			},
			[81214821] = {
				["icon"] = 4,
				["title"] = "Val'kyr Pet",
				["desc"] = "",
			},
		},
		["TheHiddenPass"] = {
			[64107467] = {
				["icon"] = 9,
				["title"] = "Black Market",
				["cont"] = 1,
				["desc"] = "Auction House",
			},
			[74587371] = {
				["icon"] = 4,
				["title"] = "The Hammer of Folly",
				["desc"] = "100g 354k ep",
			},
		},
		["ValleyoftheFourWinds"] = {
			[70116312] = {
				["title"] = "Galleon (Worldboss)",
				["icon"] = 7,
				["desc"] = "ReSpawns every 1-3 hours\nKill Check Macro:\n/run for k, v in pairs({ Galleon=32098, Sha=32099, Nalak=32518, Oon=32519, Champ=32641, Key=32626, Barrens=32862}) do print(format(\"%s: %s\", k, IsQuestFlaggedCompleted(v) and \"\\124cff00ff00Yes\" or \"\\124cffff0000No\"))",
			},
			[16347863] = {
				["icon"] = 8,
				["title"] = "Jonn-Dar",
				["desc"] = "Rare Mob\n[Terracotta Fragment]\nTrinket 400 lvl 85 Summons Pet for 10 min.",
			},
			[34174639] = {
				["title"] = "Chi-Chi",
				["icon"] = 3,
				["desc"] = "Blue Feather [Four winds stir fry]",
			},
			[56093396] = {
				["title"] = "Sele'na",
				["icon"] = 8,
				["desc"] = "Rare Mob in Moor",
			},
			[54182874] = {
				["title"] = "Sele'na",
				["icon"] = 1,
				["desc"] = "Rare Mob Spawn2",
			},
			[45894365] = {
				["icon"] = 16,
				["title"] = "Farmer Nishi",
				["desc"] = "Pet-Trainer\nWildlife, Elemental, Elemental",
			},
			[92233890] = {
				["icon"] = 4,
				["title"] = "Boat-Building Instructions",
				["desc"] = "10g Grey Item\nIn the hut\nNo treasure!",
			},
			[29032965] = {
				["icon"] = 3,
				["title"] = "NPC",
				["desc"] = "Sho= Lovely Apple [Eternal Blossom Fish]",
			},
			[41013008] = {
				["icon"] = 3,
				["title"] = "NPC",
				["desc"] = "Fishy Rohrrothe=Jadekatze [Twin Fish Platter]",
			},
			[14213521] = {
				["title"] = "Staff of the Hidden Master",
				["icon"] = 4,
				["desc"] = "= Agi Staff 419 lvl 86\n Hidden within the bamboo trees at (17.4, 36.0) North Western part of Valley of the Four Winds",
			},
			[35712586] = {
				["title"] = "Sulik'shor",
				["icon"] = 8,
				["desc"] = "Rare Mob\nDropt +500 value Item",
			},
			[46133832] = {
				["icon"] = 4,
				["title"] = "Ancient Pandaren Woodcutter",
				["desc"] = "= Grey Item 110g no EP\n Ghostly Pandaren Craftsman\nNPC-Scan: 64191",
			},
			[66545904] = {
				["title"] = "Salyin Warscout",
				["icon"] = 8,
				["desc"] = "Rare Mob\nRiverside direction Jade Forest",
			},
			[77181147] = {
				["icon"] = 9,
				["title"] = "Black Market",
				["desc"] = "Auction house",
			},
			[31045623] = {
				["title"] = "NPCs",
				["icon"] = 3,
				["desc"] = "Ella = Jade Cat  [Shrimp Dumplings]\nOld Hillpaw Feather  [Braised Turtle]",
			},
			[9594676] = {
				["title"] = "Nal'lak the Ripper",
				["icon"] = 1,
				["desc"] = "",
			},
			[16903710] = {
				["title"] = "Bonobos <The Bananamancer>",
				["icon"] = 8,
				["desc"] = "Rare Mob",
			},
			[54135345] = {
				["title"] = "NPCS",
				["icon"] = 3,
				["desc"] = "Sho = Apple [Eternal Blossom Fish]\nJogu = Apple  [Sauteed Carrots]\nFarmer Fung = Marsh Lily [Wildfowl Roast]\nGina = Marsh Lily [Swirling Mist Soup]\nChi-Chi = Feather [Valley Stir Fry]\nOld Hillpaw = Feather [Braised Turtle]\nTina Mudclaw = Ruby [Fire Spirit Salmon]\nHaohan Mudclaw = Ruby [G. Tigersteak]",
			},
			[75434703] = {
				["title"] = "Salyin Warscout",
				["icon"] = 1,
				["desc"] = "Rare Mob Spawn 2",
			},
			[43223853] = {
				["icon"] = 4,
				["title"] = "Cache of Pilfered Goods",
				["desc"] = "Its the most northern gap in the rabbit hole. theres no point going down the huge carrot and the other gap where theres a pumpkin in a cart is also not where it spawns. That aside its pretty big and hard to miss if its really there",
			},
			[47282436] = {
				["title"] = "Ancient Pandaren Fishing Charm",
				["icon"] = 4,
				["desc"] = "Ghostly Pandaren Fisherman\nNPC-Scan: 64004",
			},
			[35836823] = {
				["icon"] = 28,
				["title"] = "Stormstout Brewery",
				["desc"] = "Inctance Entrance (85-87 / 90 Heroic)",
			},
			[55274826] = {
				["icon"] = 6,
				["title"] = "Dailys",
				["desc"] = "Cooking Dailies\nGoat Mounts!",
			},
			[88141803] = {
				["title"] = "Nasra Spothide",
				["icon"] = 8,
				["desc"] = "Rare Mob\nPanda",
			},
			[48103468] = {
				["icon"] = 3,
				["title"] = "NPC",
				["desc"] = "Farmer Fung = Marsh Lily [Wildfowl Roast]",
			},
			[44823439] = {
				["icon"] = 3,
				["title"] = "NPCs ",
				["desc"] = "Haohan Mudlcaw = Ruby [G. Tigersteak]\nTina Mudclaw = Ruby [Fire Spirit Salmon]",
			},
			[36306366] = {
				["icon"] = 1,
				["title"] = "Blackhoof",
				["desc"] = "Rare Mob Spawn2",
			},
			[35715748] = {
				["title"] = "Blackhoof",
				["icon"] = 8,
				["desc"] = "Battle Hors(pull all within 40m range)\nRare Mob",
			},
			[19064253] = {
				["icon"] = 4,
				["title"] = "Staff of the Hidden Master",
				["desc"] = "...also",
			},
			[8026113] = {
				["title"] = "Nal'lak the Ripper",
				["icon"] = 1,
				["desc"] = "",
			},
			[69790556] = {
				["icon"] = 28,
				["title"] = "Terrace of Endless Spring",
				["desc"] = "Entrance 10/25 Raid",
			},
			[10115382] = {
				["title"] = "Nal'lak the Ripper",
				["icon"] = 8,
				["desc"] = "Rare Mob\nFly half circle at the gate",
			},
			[23692912] = {
				["title"] = "Virmen Treasure Cache",
				["icon"] = 4,
				["desc"] = "486k EP 98g\nIn the cave\nTreasure",
			},
		},
		["Undercity"] = {
			[67645239] = {
				["icon"] = 9,
				["level"] = 1,
				["title"] = "Auction house",
				["desc"] = "",
			},
			[73455558] = {
				["icon"] = 18,
				["level"] = 1,
				["title"] = "First Aid",
				["desc"] = "",
			},
			[69863670] = {
				["icon"] = 14,
				["level"] = 1,
				["title"] = "Mailbox",
				["desc"] = "",
			},
			[47551900] = {
				["icon"] = 17,
				["level"] = 1,
				["title"] = "Priest Trainer",
				["desc"] = "",
			},
			[85197127] = {
				["icon"] = 17,
				["level"] = 1,
				["title"] = "Rogue Trainer",
				["desc"] = "",
			},
			[54114984] = {
				["icon"] = 18,
				["level"] = 1,
				["title"] = "Herbalism",
				["desc"] = "",
			},
			[71334681] = {
				["icon"] = 9,
				["level"] = 1,
				["title"] = "Auction house",
				["desc"] = "",
			},
			[67763589] = {
				["icon"] = 9,
				["level"] = 1,
				["title"] = "Auction House",
				["desc"] = "",
			},
			[64175223] = {
				["icon"] = 9,
				["level"] = 1,
				["title"] = "Auction House",
				["desc"] = "",
			},
			[75663744] = {
				["icon"] = 18,
				["level"] = 1,
				["title"] = "Archeology",
				["desc"] = "",
			},
			[61203050] = {
				["icon"] = 18,
				["level"] = 1,
				["title"] = "Blacksmith",
				["desc"] = "",
			},
			[56443418] = {
				["icon"] = 17,
				["level"] = 1,
				["title"] = "Monk Trainer",
				["desc"] = "",
			},
			[67673788] = {
				["icon"] = 13,
				["level"] = 1,
				["title"] = "Innkeeper",
				["desc"] = "",
			},
			[58029054] = {
				["icon"] = 17,
				["level"] = 1,
				["title"] = "Paladin Trainer",
				["desc"] = "",
			},
			[46911539] = {
				["icon"] = 17,
				["level"] = 1,
				["title"] = "Warrior Trainer",
				["desc"] = "",
			},
			[71454163] = {
				["icon"] = 9,
				["level"] = 1,
				["title"] = "Auction House",
				["desc"] = "",
			},
			[47052835] = {
				["icon"] = 2,
				["level"] = 1,
				["title"] = "Practice Dummies",
				["desc"] = "",
			},
			[66983811] = {
				["icon"] = 16,
				["level"] = 1,
				["title"] = "Stable Master",
				["desc"] = "",
			},
			[69603908] = {
				["icon"] = 23,
				["level"] = 1,
				["title"] = "Reagents",
				["desc"] = "",
			},
			[70614665] = {
				["icon"] = 2,
				["level"] = 1,
				["title"] = "Barber",
				["desc"] = "",
			},
			[66725018] = {
				["icon"] = 14,
				["level"] = 1,
				["title"] = "Mailbox",
				["desc"] = "",
			},
			[66604413] = {
				["icon"] = 10,
				["level"] = 1,
				["title"] = "Bank",
				["desc"] = "",
			},
			[69564406] = {
				["icon"] = 25,
				["level"] = 1,
				["title"] = "Guild Vendor Tabrad Vendor",
				["desc"] = "",
			},
			[61886078] = {
				["icon"] = 18,
				["level"] = 1,
				["title"] = "Enchanting",
				["desc"] = "",
			},
			[47717303] = {
				["icon"] = 18,
				["level"] = 1,
				["title"] = "Alchemy Trainer",
				["desc"] = "",
			},
			[61095870] = {
				["icon"] = 18,
				["level"] = 1,
				["title"] = "Inscription",
				["desc"] = "",
			},
			[62194478] = {
				["icon"] = 18,
				["level"] = 1,
				["title"] = "Cooking Trainer",
				["desc"] = "",
			},
			[55005032] = {
				["icon"] = 17,
				["level"] = 1,
				["title"] = "Shaman and Druid Trainer",
				["desc"] = "",
			},
			[60494665] = {
				["icon"] = 9,
				["level"] = 1,
				["title"] = "Auction House",
				["desc"] = "",
			},
			[55993677] = {
				["title"] = "Jewellcrafter/Miner",
				["level"] = 1,
				["icon"] = 18,
				["desc"] = "",
			},
			[61805168] = {
				["icon"] = 14,
				["level"] = 1,
				["title"] = "Mailbox",
				["desc"] = "",
			},
			[70565885] = {
				["icon"] = 18,
				["level"] = 1,
				["title"] = "Leatherworker\\Skinner",
				["desc"] = "",
			},
			[55468566] = {
				["icon"] = 11,
				["level"] = 1,
				["title"] = "Battlemaster",
				["desc"] = "",
			},
			[64253588] = {
				["icon"] = 9,
				["level"] = 1,
				["title"] = "Auction House",
				["desc"] = "",
			},
			[62193619] = {
				["icon"] = 14,
				["level"] = 1,
				["title"] = "Mailbox",
				["desc"] = "",
			},
			[84961034] = {
				["icon"] = 17,
				["level"] = 1,
				["title"] = "Mage Trainer",
				["desc"] = "",
			},
			[70742943] = {
				["icon"] = 18,
				["level"] = 1,
				["title"] = "Tailoring",
				["desc"] = "",
			},
			[76187387] = {
				["icon"] = 18,
				["level"] = 1,
				["title"] = "Engineering Trainer",
				["desc"] = "",
			},
			[80883113] = {
				["icon"] = 18,
				["level"] = 1,
				["title"] = "Fishing Trainer",
				["desc"] = "",
			},
			[56201629] = {
				["icon"] = 17,
				["level"] = 1,
				["title"] = "Mage Trainer",
				["desc"] = "",
			},
			[84101564] = {
				["icon"] = 28,
				["level"] = 1,
				["title"] = "Portal Trainer",
				["desc"] = "",
			},
			[71636168] = {
				["icon"] = 14,
				["level"] = 1,
				["title"] = "Mailbox",
				["desc"] = "",
			},
			[85151703] = {
				["icon"] = 28,
				["level"] = 1,
				["title"] = "Portal to Blasted Lands",
				["desc"] = "",
			},
			[60564142] = {
				["icon"] = 9,
				["level"] = 1,
				["title"] = "Auction House",
				["desc"] = "",
			},
			[69905193] = {
				["icon"] = 14,
				["level"] = 1,
				["title"] = "Mailbox",
				["desc"] = "",
			},
		},
		["ZulDrak"] = {
			[23796424] = {
				["title"] = "Val'kyr Pet",
				["icon"] = 4,
				["desc"] = "",
			},
			[13116681] = {
				["title"] = "Gutretch <Master Pet Tamer>",
				["icon"] = 16,
				["desc"] = "Pet-Trainer\nWildlife, Critter, Wildlife",
			},
			[58013938] = {
				["title"] = "Val'kyr Pet",
				["icon"] = 4,
				["desc"] = "",
			},
			[74912238] = {
				["title"] = "Val'kyr Pet",
				["icon"] = 4,
				["desc"] = "",
			},
		},
		["Durotar"] = {
			[48944027] = {
				["icon"] = 10,
				["title"] = "Ravika",
				["desc"] = "Pet: [Gahz'rooki]",
			},
			[52014189] = {
				["icon"] = 16,
				["level"] = 1,
				["title"] = "Stable Master",
				["desc"] = "",
			},
			[51934214] = {
				["icon"] = 14,
				["level"] = 1,
				["title"] = "Mailbox",
				["desc"] = "",
			},
			[51524165] = {
				["icon"] = 13,
				["level"] = 1,
				["title"] = "Innkeeper",
				["desc"] = "",
			},
			[56597304] = {
				["icon"] = 15,
				["level"] = 1,
				["title"] = "Repair",
				["desc"] = "",
			},
			[55727370] = {
				["icon"] = 21,
				["level"] = 1,
				["title"] = "Butcher",
				["desc"] = "",
			},
			[56027446] = {
				["icon"] = 14,
				["level"] = 1,
				["title"] = "Mailbox",
				["desc"] = "",
			},
			[52904121] = {
				["icon"] = 15,
				["level"] = 1,
				["title"] = "Repair",
				["desc"] = "",
			},
		},
		["TownlongWastes"] = {
			[32786216] = {
				["title"] = "Fragment of Dread",
				["icon"] = 4,
				["desc"] = "90g Grey Item 431k XP\nIn the cave 48.49, 89.46\nCounts as treasure",
			},
			[57475831] = {
				["title"] = "Hardened Sap of Kri'vess",
				["icon"] = 4,
				["desc"] = "110g Grey Item 420k XP\nSpawns: 52,60 53,58 53,61 56,55 57,41\nCounts as treasure",
			},
			[61753463] = {
				["icon"] = 8,
				["title"] = "Kah'tir",
				["desc"] = "Rare Mob",
			},
			[32586087] = {
				["title"] = "Yul Wildpaw",
				["icon"] = 8,
				["desc"] = "Evil Rare Panda",
			},
			[66724781] = {
				["icon"] = 8,
				["title"] = "Lon the Bull",
				["desc"] = "Rare Mob",
			},
			[66727393] = {
				["icon"] = 8,
				["title"] = "The Yowler",
				["desc"] = "Rare Mob\nMonkey",
			},
			[46697420] = {
				["icon"] = 8,
				["title"] = "Lith'ik the Stalker",
				["desc"] = "Rare Mob\ngrasshopper",
			},
			[36215219] = {
				["title"] = "Seeker Zusshi <Grand Master Pet Tamer>",
				["icon"] = 16,
				["desc"] = "Critter, Aquatik, Elemental",
			},
			[67564790] = {
				["title"] = "Yaungol Fire Carrier",
				["icon"] = 4,
				["desc"] = "= 1h Strength Mace 450 lvl 86\nThe small torch lying around in a tray",
			},
			[58708543] = {
				["title"] = "Siltriss the Sharpener",
				["icon"] = 8,
				["desc"] = "Rare Mob",
			},
			[62773393] = {
				["title"] = "Abandoned Crate of Goods",
				["icon"] = 4,
				["desc"] = "Box contains approximately. 103g\nin tent at 62.82 34.05\nCounts as treasure",
			},
			[51707157] = {
				["icon"] = 6,
				["title"] = "Dailys Shado-Pan",
				["desc"] = "",
			},
			[36958540] = {
				["title"] = "Zandalari Warbringer & Warscout",
				["cont"] = 1,
				["icon"] = 8,
				["desc"] = "5.2 Rare Mob - Drops Mount\nJade, Slate, Amber, or Golden Primordial Direhorn\nNPC-Scan id: 69769 & 69768",
			},
			[56914229] = {
				["title"] = "Burning Pandaren Spirit",
				["cont"] = 1,
				["icon"] = 16,
				["desc"] = "Pet-Trainer\nElemental, Dragonkin, Flying",
			},
			[28772436] = {
				["icon"] = 28,
				["title"] = "Portal",
				["desc"] = "Prequest portal around the island\n(important for Dailys Shado-Pan)",
			},
			[67134449] = {
				["title"] = "Yaungol Fire Carrier",
				["icon"] = 4,
				["desc"] = "= 1h Strength Mace 450 lvl 86\nThe small torch lying around",
			},
			[63238857] = {
				["title"] = "Eshelon",
				["icon"] = 8,
				["desc"] = "Rare Mob",
			},
			[53276409] = {
				["title"] = "Norlaxx",
				["icon"] = 8,
				["desc"] = "Rare Mob",
			},
			[46008889] = {
				["icon"] = 1,
				["title"] = "Lith'ik the Stalker",
				["desc"] = "Spawn 2",
			},
			[50527291] = {
				["icon"] = 28,
				["title"] = "Portal to the island of Thunder",
				["desc"] = "",
			},
			[35258276] = {
				["title"] = "Siege of Niuzao temple",
				["icon"] = 28,
				["desc"] = "Instance Entrance (90 Heroic)",
			},
			[69029007] = {
				["title"] = "Eshelon",
				["icon"] = 1,
				["desc"] = "Rare Mob Spawn 2",
			},
			[52675574] = {
				["title"] = "Hardened Sap of Kri'vess",
				["icon"] = 4,
				["desc"] = "110g Grey Item 420k XP\nSpawns: 52,60 53,58 53,61 56,55 57,41\nCounts as treasure",
			},
			[65878654] = {
				["icon"] = 4,
				["title"] = "Amber Encased Moth",
				["desc"] = "105g Grey Item 451k XP\nCounts as treasure!",
			},
		},
		["TimelessIsle"] = {
			[33385436] = {
				["icon"] = 20,
				["title"] = "Cloudstrike Family Helm 18",
				["desc"] = "",
			},
			[65354923] = {
				["icon"] = 6,
				["title"] = "Daily",
				["desc"] = "A Timeless Question = 100 Coins",
			},
			[55195035] = {
				["title"] = "Cloudstrike Family Helm 8",
				["icon"] = 20,
				["desc"] = "",
			},
			[64497249] = {
				["title"] = "Cloudstrike Family Helm 5",
				["icon"] = 20,
				["desc"] = "",
			},
			[55197281] = {
				["icon"] = 20,
				["title"] = "Cloudstrike Family Helm 14",
				["desc"] = "",
			},
			[51386232] = {
				["title"] = "Cloudstrike Family Helm 9",
				["icon"] = 20,
				["desc"] = "",
			},
			[37234185] = {
				["title"] = "Cloudstrike Family Helm 10",
				["icon"] = 20,
				["desc"] = "",
			},
			[47388099] = {
				["title"] = "Cloudstrike Family Helm 4",
				["icon"] = 20,
				["desc"] = "",
			},
			[65465276] = {
				["icon"] = 20,
				["title"] = "Cloudstrike Family Helm 16",
				["desc"] = "",
			},
			[39267778] = {
				["title"] = "Cloudstrike Family Helm 3",
				["icon"] = 20,
				["desc"] = "",
			},
			[63104554] = {
				["title"] = "Cloudstrike Family Helm 6",
				["icon"] = 20,
				["desc"] = "",
			},
			[37417413] = {
				["title"] = "Shrine",
				["icon"] = 1,
				["desc"] = "",
			},
			[33063271] = {
				["title"] = "Cloudstrike Family Helm 1",
				["icon"] = 20,
				["desc"] = "10 Min Buff\nFor Achievement [Legend of the Past]\nCave of Rare Mob Speluk can be opened with ability granted from helm",
			},
			[48775115] = {
				["icon"] = 20,
				["title"] = "Cloudstrike Family Helm 17",
				["desc"] = "",
			},
			[22893865] = {
				["icon"] = 20,
				["title"] = "Cloudstrike Family Helm 11",
				["desc"] = "",
			},
			[42895645] = {
				["icon"] = 20,
				["title"] = "Cloudstrike Family Helm 19",
				["desc"] = "",
			},
			[42875522] = {
				["title"] = "Daily",
				["icon"] = 6,
				["desc"] = "Path of the Mistwalker - Kill 20 Elite's",
			},
			[55735933] = {
				["title"] = "Cloudstrike Family Helm 7",
				["icon"] = 20,
				["desc"] = "",
			},
			[36914714] = {
				["title"] = "Mailbox",
				["icon"] = 14,
				["desc"] = "",
			},
			[50167313] = {
				["icon"] = 20,
				["title"] = "Cloudstrike Family Helm 13",
				["desc"] = "",
			},
			[32066192] = {
				["title"] = "Cloudstrike Family Helm 2",
				["icon"] = 20,
				["desc"] = "",
			},
			[25577185] = {
				["icon"] = 20,
				["title"] = "Cloudstrike Family Helm 12",
				["desc"] = "",
			},
			[68246046] = {
				["title"] = "Cloudstrike Family Helm 15",
				["icon"] = 20,
				["desc"] = "",
			},
			[28047187] = {
				["title"] = "Shrine",
				["icon"] = 1,
				["desc"] = "",
			},
			[49807040] = {
				["title"] = "Shrine",
				["icon"] = 1,
				["desc"] = "",
			},
		},
		["TheJadeForest"] = {
			[56797184] = {
				["title"] = "Urobi the Walker",
				["icon"] = 8,
				["desc"] = "Rare Mob\n14% Epic Agi Staff 420 lvl 85 BoP",
			},
			[38954684] = {
				["icon"] = 4,
				["title"] = "Jade Infused Blade",
				["desc"] = "1h Strength Sword 404 lvl 85\nJade statue with sword in hand 39.26 46.65",
			},
			[54004546] = {
				["icon"] = 8,
				["title"] = "Ferdinand",
				["desc"] = "Rare Mob\nPossible Epic Drop",
			},
			[23363522] = {
				["title"] = "Pandaren Ritual Stone",
				["icon"] = 4,
				["desc"] = "105g Grey Item + 153k XP",
			},
			[38506348] = {
				["title"] = "Krax'ik",
				["icon"] = 8,
				["desc"] = "Rare Mob\n15% Epic 1h Agi Axt 420 lvl 85 BoP",
			},
			[31792824] = {
				["title"] = "Lucky Pandaren Coin",
				["icon"] = 4,
				["desc"] = "95g Grey Item 190k XP\nin fountain at 31.9, 27.8\n",
			},
			[46108061] = {
				["title"] = "Offering of Remembrance",
				["icon"] = 4,
				["desc"] = "Contains 30g + 95k XP\nLocated on the shrine 46.3, 80.7\nNo treasure!",
			},
			[33975068] = {
				["title"] = "Aethis",
				["icon"] = 8,
				["desc"] = "Rare Mob\n15% Epic 1h Will Mace 420 lvl 85 BoP",
			},
			[41461620] = {
				["title"] = "Morgrinn Crackfang",
				["icon"] = 8,
				["desc"] = "Rare Mob\n3 spawns in area\n15% Epic 2h Strength Mace 420 lvl 85",
			},
			[51279905] = {
				["title"] = "Ship's Locker",
				["icon"] = 4,
				["desc"] = "Contains 96g \nUnderwater in Ship 51.2, 100.0\nCounts as treasure!",
			},
			[55223240] = {
				["title"] = "Martar the Not-So-Smart",
				["icon"] = 8,
				["desc"] = "Rare Mob\n32% Trinket: Summons 10min Hogger Pet",
			},
			[43807542] = {
				["title"] = "Kor'nas Nightsavage",
				["icon"] = 8,
				["desc"] = "Rare Mob\n14% Epic Int/Hit Staff 420 lvl 85 BoP",
			},
			[47865410] = {
				["title"] = "Hyuna of the Shrines <Grand Master Pet Tamer>",
				["icon"] = 16,
				["desc"] = "Pet-Trainer\nWildlife, Flying, Aquatic",
			},
			[64287446] = {
				["title"] = "Sarnak",
				["icon"] = 8,
				["desc"] = "Rare Mob\nIn the cave\nEpic Agi Crossbow 420 lvl 85 BoE",
			},
			[28823618] = {
				["title"] = "Whispering Pandaren Spirit <Grand Master Pet Tamer>",
				["cont"] = 1,
				["icon"] = 16,
				["desc"] = "Pet-Trainer\nElemental, Dragonkin, Critter",
			},
			[42291139] = {
				["icon"] = 4,
				["title"] = "Hammer of Ten Thunders",
				["desc"] = "= 2h Mace Strength 404 lvl 85\n2 Spawns: 41.8 17.6 and 43.0 11.6",
			},
			[45641829] = {
				["title"] = "Morgrinn Crackfang",
				["icon"] = 1,
				["desc"] = "Rare Mob Spawn 2\n3 Spawns in this area\n15% Epic 2h Strength Mace 420 lvl 85",
			},
			[45802831] = {
				["icon"] = 4,
				["title"] = "Ancient Pandaren Mining Pick",
				["desc"] = "= 1h Axt Strength 404 lvl 85\nPrecious stone pickaxe for mining\nIn the cave stuck in a stone\n",
			},
			[42333893] = {
				["title"] = "Mister Ferocious",
				["icon"] = 8,
				["desc"] = "Rare Mob Monkey\n16% Epic 1h Strength Mace BoP",
			},
			[45547111] = {
				["icon"] = 4,
				["title"] = "Ancient Jinyu Staff",
				["desc"] = "= Staff Intelligenz 404 lvl 85\nUnderwater in This can be found up and down the entire river that runs between Grookin Hill and Pearlfin Village\n3 Spawns: 47.1 67.4 / 46.2 71.2 / 44.9 64.6\n",
			},
			[62402728] = {
				["title"] = "Stash of Gems",
				["icon"] = 4,
				["desc"] = "6g + gems\nCaveEntrance:  62.6 26.7\nJewel box: 62.45 27.52",
			},
			[56094703] = {
				["icon"] = 6,
				["title"] = "Dailys",
				["desc"] = "Order of the Cloud Serpent\nMounts!",
			},
			[26143201] = {
				["title"] = "Ancient Pandaren Tea Pot",
				["icon"] = 4,
				["desc"] = "100g Grey Item + 303 XP\nIs on the table 26.2, 32,3",
			},
			[41091777] = {
				["icon"] = 4,
				["title"] = "Hammer of Ten Thunders",
				["desc"] = "= 2h Mace Strength 404 lvl 85\n2 Spawns: 41.8 17.6 and 43.0 11.6",
			},
			[55566579] = {
				["title"] = "Dailys",
				["icon"] = 6,
				["desc"] = "Golden Lotus:\nThe Celestial Exalted",
			},
			[39340732] = {
				["title"] = "Wodin's Mantid Shanker",
				["icon"] = 4,
				["desc"] = "1h Agi dagger 404 lvl 85\nin fountain 39.4 7.3",
			},
			[56115777] = {
				["title"] = "The Temple of the Jade Serpent",
				["icon"] = 28,
				["desc"] = "Instance Entrance (85-87 / 90 Heroic)",
			},
			[53461963] = {
				["title"] = "Zandalari Warbringer & Warscout",
				["cont"] = 1,
				["icon"] = 8,
				["desc"] = "5.2 Rare Mob - Drops Mount\nJade, Slate, Amber, or Golden Prinordial Direhorn\nNPC-Scan id: 69842, 69769, 69841 & 69768",
			},
		},
		["SwampOfSorrows"] = {
			[47325549] = {
				["icon"] = 16,
				["level"] = 1,
				["title"] = "Stable Master",
				["desc"] = "",
			},
			[46825708] = {
				["icon"] = 13,
				["level"] = 1,
				["title"] = "Innkeeper",
				["desc"] = "",
			},
		},
		["Pandaria"] = {
			[52343981] = {
				["icon"] = 7,
				["title"] = "Sha of Wrath(Worldboss)",
				["desc"] = "ReSpawns every 15-30 min",
			},
			[56916985] = {
				["icon"] = 7,
				["title"] = "Galleon (Worldboss)",
				["desc"] = "ReSpawns every 1-3 hours",
			},
		},
		["TwilightHighlands"] = {
			[56525639] = {
				["icon"] = 16,
				["title"] = "Goz Banefury <Master Pet Tamer>",
				["desc"] = "Pet-Trainer\nWildlife, Magical, Elemental",
			},
		},
		["Ashenvale"] = {
			[12733386] = {
				["icon"] = 16,
				["level"] = 1,
				["title"] = "Stable Master",
				["desc"] = "",
			},
			[11643549] = {
				["icon"] = 15,
				["level"] = 1,
				["title"] = "Repair",
				["desc"] = "",
			},
			[50566584] = {
				["icon"] = 15,
				["level"] = 1,
				["title"] = "Repair",
				["desc"] = "",
			},
			[50776555] = {
				["icon"] = 23,
				["level"] = 1,
				["title"] = "Reagents",
				["desc"] = "",
			},
			[74006065] = {
				["icon"] = 13,
				["level"] = 1,
				["title"] = "Innkeeper",
				["desc"] = "",
			},
			[12203246] = {
				["icon"] = 23,
				["level"] = 1,
				["title"] = "Reagents",
				["desc"] = "",
			},
			[38604224] = {
				["icon"] = 13,
				["level"] = 1,
				["title"] = "Innkeeper",
				["desc"] = "",
			},
			[38684235] = {
				["icon"] = 16,
				["level"] = 1,
				["title"] = "Stable Master",
				["desc"] = "",
			},
			[50226608] = {
				["icon"] = 14,
				["level"] = 1,
				["title"] = "Mailbox",
				["desc"] = "",
			},
			[50346601] = {
				["icon"] = 16,
				["level"] = 1,
				["title"] = "Stable Master",
				["desc"] = "",
			},
			[73286069] = {
				["icon"] = 16,
				["level"] = 1,
				["title"] = "Stable Master",
				["desc"] = "",
			},
			[50436715] = {
				["icon"] = 13,
				["level"] = 1,
				["title"] = "Innkeeper",
				["desc"] = "",
			},
			[12783408] = {
				["icon"] = 14,
				["level"] = 1,
				["title"] = "Mailbox",
				["desc"] = "",
			},
			[13003418] = {
				["icon"] = 13,
				["level"] = 1,
				["title"] = "Innkeeper",
				["desc"] = "",
			},
			[37904378] = {
				["icon"] = 15,
				["level"] = 1,
				["title"] = "Repair",
				["desc"] = "",
			},
			[73616094] = {
				["icon"] = 14,
				["level"] = 1,
				["title"] = "Mailbox",
				["desc"] = "",
			},
			[74266053] = {
				["icon"] = 15,
				["level"] = 1,
				["title"] = "Repair",
				["desc"] = "",
			},
		},
		["IsleoftheThunderKing"] = {
			[52238939] = {
				["icon"] = 9,
				["title"] = "Treasure of the Thunder King",
				["desc"] = "51.5, 89.6",
			},
			[52927710] = {
				["title"] = "Treasure of the Thunder King",
				["icon"] = 9,
				["desc"] = "52.9, 77.2",
			},
			[48458931] = {
				["icon"] = 8,
				["title"] = "Haywire Sunreaver Construct",
				["desc"] = "Rare Mob\nNPC-Scan: 50358",
			},
			[48178253] = {
				["title"] = "Treasure of the Thunder King",
				["icon"] = 9,
				["desc"] = "47.9, 82.1",
			},
			[33636176] = {
				["icon"] = 9,
				["title"] = "Treasure of the Thunder King",
				["desc"] = "33.6, 60.4",
			},
			[35304723] = {
				["title"] = "Treasure of the Thunder King",
				["icon"] = 9,
				["desc"] = "35.3, 47,7",
			},
			[43506744] = {
				["icon"] = 9,
				["title"] = "Treasure of the Thunder King",
				["desc"] = "44.3, 67.5",
			},
			[28918093] = {
				["icon"] = 9,
				["title"] = "Treasure of the Thunder King",
				["desc"] = "28.9, 80.8",
			},
			[41007478] = {
				["icon"] = 9,
				["title"] = "Treasure of the Thunder King",
				["desc"] = "40.8, 74.7",
			},
			[56178452] = {
				["icon"] = 1,
				["title"] = "Haywire Sunreaver Construct",
				["desc"] = "Rare Mob spawn 2\nNPC-Scan: 50358",
			},
			[53938286] = {
				["icon"] = 9,
				["title"] = "Treasure of the Thunder King",
				["desc"] = "53.8, 82.8",
			},
			[37166808] = {
				["title"] = "Treasure of the Thunder King",
				["icon"] = 9,
				["desc"] = "37.0, 68.1",
			},
			[50292514] = {
				["title"] = "Backbreaker Uru",
				["icon"] = 8,
				["desc"] = "Rare Mob (Phase 4)\nNPCScan: 70001",
			},
			[39818207] = {
				["title"] = "Ra'sha",
				["icon"] = 8,
				["desc"] = "Rare Mob\nNPCScan: 70530\nDrops Ra'sha's Sacrificial Dagger",
			},
			[54415354] = {
				["icon"] = 9,
				["title"] = "Treasure of the Thunder King",
				["desc"] = "54.1, 53.6",
			},
			[61835015] = {
				["title"] = "God-Hulk Ramuk",
				["icon"] = 8,
				["desc"] = "Rare Mob (Phase 3)\nNPCScan: 69999",
			},
			[61083876] = {
				["title"] = "Molthor <The Gatekeeper>",
				["icon"] = 8,
				["desc"] = "Rare Mob (Phase 4)\nNPCScan: 70003 ",
			},
			[44248276] = {
				["title"] = "Treasure of the Thunder King",
				["icon"] = 9,
				["desc"] = "43.8, 82.8",
			},
			[50967126] = {
				["icon"] = 8,
				["title"] = "Progenitus <The Firstborn>",
				["desc"] = "Rare Mob\nNPC-Scan: 69997",
			},
			[45315083] = {
				["title"] = "Treasure of the Thunder King",
				["icon"] = 9,
				["desc"] = "45.2, 50.7",
			},
			[33395770] = {
				["icon"] = 9,
				["title"] = "Treasure of the Thunder King",
				["desc"] = "33.4, 57.5",
			},
			[50314676] = {
				["icon"] = 10,
				["title"] = "Hand in for Points",
				["desc"] = "& Entrance for 10/25 Throne of Thunder",
			},
			[47447239] = {
				["title"] = "Treasure of the Thunder King",
				["icon"] = 9,
				["desc"] = "47.4, 72.4",
			},
			[33077103] = {
				["icon"] = 9,
				["title"] = "Treasure of the Thunder King",
				["desc"] = "33.6, 71.7",
			},
			[35236168] = {
				["icon"] = 8,
				["title"] = "Mumta <Thief of Souls>",
				["desc"] = "Rare Mob\nNPCScan: 69664",
			},
			[53345394] = {
				["icon"] = 8,
				["title"] = "Goda",
				["desc"] = "Rare Mob\nNPCScan: 69998",
			},
			[54133507] = {
				["title"] = "Lu-Ban",
				["icon"] = 8,
				["desc"] = "Rare Mob (Phase 4)\nNPCScan: 70002",
			},
			[38877702] = {
				["icon"] = 9,
				["title"] = "Treasure of the Thunder King",
				["desc"] = "39.1, 76.8",
			},
			[46545722] = {
				["icon"] = 9,
				["title"] = "Treasure of the Thunder King",
				["desc"] = "46.3, 57.5",
			},
			[43367820] = {
				["title"] = "Treasure of the Thunder King",
				["icon"] = 9,
				["desc"] = "43.5, 78.6",
			},
			[51437494] = {
				["icon"] = 9,
				["title"] = "Treasure of the Thunder King",
				["desc"] = "51.5, 74.0",
			},
			[37228196] = {
				["icon"] = 8,
				["title"] = "Ku'lai the Skyclaw <Ward of Beasts>",
				["desc"] = "Rare Mob\nNPCScan: 69996",
			},
			[44145602] = {
				["title"] = "Treasure of the Thunder King",
				["icon"] = 9,
				["desc"] = "",
			},
			[35466400] = {
				["icon"] = 9,
				["title"] = "Treasure of the Thunder King",
				["desc"] = "35.6. 63.7",
			},
			[46806153] = {
				["icon"] = 9,
				["title"] = "Treasure of the Thunder King",
				["desc"] = "46.6, 61.6",
			},
			[33607630] = {
				["icon"] = 9,
				["title"] = "Treasure of the Thunder King",
				["desc"] = "33.4, 76.3",
			},
			[38765961] = {
				["icon"] = 9,
				["title"] = "Treasure of the Thunder King",
				["desc"] = "37.9, 61.0 / 38.7, 59.6 / 36.9, 60.7 / 36.1, 58.5",
			},
			[44543008] = {
				["icon"] = 8,
				["title"] = "Al'tabim the All-Seeing",
				["desc"] = "Rare Mob\nNPCScan: 52689",
			},
		},
		["Dragonblight"] = {
			[59207727] = {
				["title"] = "Okrut Dragonwaste <Master Pet Tamer>",
				["icon"] = 16,
				["desc"] = "Pet-Trainer\nUndead, Dragonkin, Undead",
			},
			[82186569] = {
				["title"] = "Val'kyr Pet",
				["icon"] = 4,
				["desc"] = "",
			},
			[26795334] = {
				["title"] = "Val'kyr Pet",
				["icon"] = 4,
				["desc"] = "",
			},
			[65283489] = {
				["title"] = "Val'kyr Pet",
				["icon"] = 4,
				["desc"] = "",
			},
		},
		["VashjirDepths"] = {
			[40917082] = {
				["icon"] = 8,
				["title"] = "Poseidus",
				["desc"] = "",
			},
		},
		["GrizzlyHills"] = {
			[61121821] = {
				["title"] = "Val'kyr Pet",
				["icon"] = 4,
				["desc"] = "",
			},
			[25935591] = {
				["title"] = "Val'kyr Pet",
				["icon"] = 4,
				["desc"] = "",
			},
			[79185238] = {
				["title"] = "Val'kyr Pet",
				["icon"] = 4,
				["desc"] = "",
			},
		},
		["IcecrownGlacier"] = {
			[73736489] = {
				["icon"] = 4,
				["title"] = "Val'kyr Pet",
				["desc"] = "",
			},
			[48398669] = {
				["icon"] = 4,
				["title"] = "Val'kyr Pet",
				["desc"] = "",
			},
			[44543377] = {
				["icon"] = 4,
				["title"] = "Val'kyr Pet",
				["desc"] = "",
			},
			[77361997] = {
				["title"] = "Major Payne",
				["icon"] = 16,
				["desc"] = "Pet-Trainer\nWildlife, Elemental, Mechanical",
			},
		},
		["Naxxramas"] = {
			[38952870] = {
				["icon"] = 8,
				["level"] = 5,
				["title"] = "Gluth",
				["desc"] = "Pet: Stitched Pup",
			},
			[76271202] = {
				["icon"] = 8,
				["level"] = 5,
				["title"] = "Maexxna",
				["desc"] = "Pet: Giant Bone Spider",
			},
			[81195757] = {
				["title"] = "Loatheb",
				["level"] = 5,
				["icon"] = 8,
				["desc"] = "Pet: Fungal Abomination",
			},
		},
		["Orgrimmar"] = {
			[69913182] = {
				["title"] = "Brawlers Guild",
				["level"] = 1,
				["icon"] = 27,
				["desc"] = "",
			},
			[47375335] = {
				["title"] = "Mailbox",
				["level"] = 1,
				["icon"] = 14,
				["desc"] = "",
			},
			[37287789] = {
				["title"] = "Auctioneer",
				["level"] = 1,
				["icon"] = 9,
				["desc"] = "",
			},
			[51464931] = {
				["title"] = "Mailbox",
				["level"] = 1,
				["icon"] = 14,
				["desc"] = "",
			},
			[66695022] = {
				["title"] = "Mailbox",
				["level"] = 1,
				["icon"] = 14,
				["desc"] = "",
			},
			[66773678] = {
				["title"] = "Auction House",
				["level"] = 1,
				["icon"] = 9,
				["desc"] = "",
			},
			[42504918] = {
				["title"] = "Auction house",
				["level"] = 1,
				["icon"] = 9,
				["desc"] = "",
			},
			[46166445] = {
				["title"] = "Portal to Blasted Lands",
				["level"] = 2,
				["icon"] = 28,
				["desc"] = "",
			},
			[46507293] = {
				["title"] = "Repair",
				["level"] = 1,
				["icon"] = 15,
				["desc"] = "",
			},
			[71305022] = {
				["icon"] = 13,
				["level"] = 1,
				["title"] = "Innkeeper",
				["desc"] = "",
			},
			[48245897] = {
				["title"] = "Flight Trainer",
				["level"] = 1,
				["icon"] = 18,
				["desc"] = "",
			},
			[33196458] = {
				["title"] = "Innkeeper",
				["level"] = 1,
				["icon"] = 13,
				["desc"] = "",
			},
			[50427280] = {
				["title"] = "Food and drink",
				["level"] = 1,
				["icon"] = 21,
				["desc"] = "",
			},
			[48248063] = {
				["title"] = "Mailbox",
				["level"] = 1,
				["icon"] = 14,
				["desc"] = "",
			},
			[41208050] = {
				["title"] = "Stable Master",
				["level"] = 1,
				["icon"] = 16,
				["desc"] = "",
			},
			[53647502] = {
				["title"] = "Mailbox",
				["level"] = 1,
				["icon"] = 14,
				["desc"] = "",
			},
			[39376523] = {
				["title"] = "Mailbox",
				["level"] = 1,
				["icon"] = 14,
				["desc"] = "",
			},
			[39287867] = {
				["title"] = "Banker",
				["level"] = 1,
				["icon"] = 10,
				["desc"] = "",
			},
			[36676497] = {
				["title"] = "Mailbox",
				["level"] = 1,
				["icon"] = 14,
				["desc"] = "",
			},
			[54864618] = {
				["title"] = "Alchemy",
				["level"] = 1,
				["icon"] = 18,
				["desc"] = "",
			},
			[39896105] = {
				["title"] = "Barber",
				["level"] = 1,
				["icon"] = 1,
				["desc"] = "",
			},
			[50687554] = {
				["title"] = "Mailbox",
				["level"] = 1,
				["icon"] = 14,
				["desc"] = "",
			},
			[48167528] = {
				["title"] = "Guild Vendor",
				["level"] = 1,
				["icon"] = 23,
				["desc"] = "",
			},
			[60425870] = {
				["title"] = "Tailoring",
				["level"] = 1,
				["icon"] = 18,
				["desc"] = "",
			},
			[53647345] = {
				["title"] = "Auction house",
				["level"] = 1,
				["icon"] = 9,
				["desc"] = "",
			},
			[60515427] = {
				["title"] = "Leatherworker/Skinning",
				["level"] = 1,
				["icon"] = 18,
				["desc"] = "",
			},
			[62164866] = {
				["title"] = "Training Dummies",
				["level"] = 1,
				["icon"] = 25,
				["desc"] = "",
			},
			[43723717] = {
				["title"] = "Reagents",
				["level"] = 2,
				["icon"] = 23,
				["desc"] = "",
			},
			[50775518] = {
				["title"] = "Zeppelin to Trisfal",
				["level"] = 1,
				["icon"] = 3,
				["desc"] = "",
			},
			[32416340] = {
				["title"] = "Auctioneer",
				["level"] = 1,
				["icon"] = 9,
				["desc"] = "",
			},
			[61643456] = {
				["title"] = "Stable Master",
				["level"] = 1,
				["icon"] = 16,
				["desc"] = "",
			},
			[67475153] = {
				["title"] = "Bank",
				["level"] = 1,
				["icon"] = 10,
				["desc"] = "",
			},
			[44505296] = {
				["title"] = "Tauren Class Trainers",
				["level"] = 1,
				["icon"] = 17,
				["desc"] = "",
			},
			[56426040] = {
				["title"] = "Cooking",
				["level"] = 1,
				["icon"] = 18,
				["desc"] = "",
			},
			[66604148] = {
				["title"] = "Fishing Trainer",
				["level"] = 1,
				["icon"] = 18,
				["desc"] = "",
			},
			[55995596] = {
				["title"] = "Engineering",
				["level"] = 1,
				["icon"] = 18,
				["desc"] = "",
			},
			[56516601] = {
				["title"] = "Mailbox",
				["level"] = 1,
				["icon"] = 14,
				["desc"] = "",
			},
			[40946993] = {
				["title"] = "Mailbox",
				["level"] = 1,
				["icon"] = 14,
				["desc"] = "",
			},
			[50513678] = {
				["title"] = "Cataclysm Portals",
				["level"] = 1,
				["icon"] = 28,
				["desc"] = "",
			},
			[38334879] = {
				["title"] = "Innkeeper",
				["level"] = 1,
				["icon"] = 13,
				["desc"] = "",
			},
			[68953991] = {
				["title"] = "Portal to Pandaria",
				["level"] = 1,
				["icon"] = 28,
				["desc"] = "",
			},
			[33636627] = {
				["title"] = "Mailbox",
				["level"] = 1,
				["icon"] = 14,
				["desc"] = "",
			},
			[47207423] = {
				["title"] = "Tabard Vendor",
				["level"] = 1,
				["icon"] = 3,
				["desc"] = "",
			},
			[54685022] = {
				["title"] = "Herbalism",
				["level"] = 1,
				["icon"] = 18,
				["desc"] = "",
			},
			[55035479] = {
				["title"] = "Inscription",
				["level"] = 1,
				["icon"] = 18,
				["desc"] = "",
			},
			[49118259] = {
				["title"] = "Bank",
				["level"] = 1,
				["icon"] = 10,
				["desc"] = "",
			},
			[43206419] = {
				["title"] = "Zeppelin to Thunder Bluff",
				["level"] = 1,
				["icon"] = 3,
				["desc"] = "",
			},
			[74264487] = {
				["title"] = "Hall of the Brave",
				["level"] = 1,
				["icon"] = 25,
				["desc"] = "",
			},
			[42505910] = {
				["title"] = "Mailbox",
				["level"] = 1,
				["icon"] = 14,
				["desc"] = "",
			},
			[39724539] = {
				["title"] = "Bank",
				["level"] = 1,
				["icon"] = 10,
				["desc"] = "",
			},
			[53818115] = {
				["title"] = "General Store",
				["level"] = 1,
				["icon"] = 21,
				["desc"] = "",
			},
			[58166627] = {
				["title"] = "Void Storage/Transmog",
				["level"] = 1,
				["icon"] = 25,
				["desc"] = "",
			},
			[31716379] = {
				["title"] = "Banker",
				["level"] = 1,
				["icon"] = 10,
				["desc"] = "",
			},
			[75393417] = {
				["title"] = "Blacksmith",
				["level"] = 1,
				["icon"] = 18,
				["desc"] = "",
			},
			[72173443] = {
				["title"] = "Jeweller/Miner",
				["level"] = 1,
				["icon"] = 18,
				["desc"] = "",
			},
			[44686197] = {
				["icon"] = 3,
				["level"] = 1,
				["title"] = "Zeppelin to Borean Tundra",
				["desc"] = "",
			},
			[52515401] = {
				["title"] = "Zeppelin to STV",
				["level"] = 1,
				["icon"] = 3,
				["desc"] = "",
			},
			[53645923] = {
				["title"] = "Battle Pet Trainer",
				["level"] = 1,
				["icon"] = 18,
				["desc"] = "",
			},
			[48427097] = {
				["title"] = "Grommosh Hold",
				["level"] = 1,
				["icon"] = 25,
				["desc"] = "",
			},
			[38857097] = {
				["title"] = "Hall of Legends",
				["level"] = 1,
				["icon"] = 25,
				["desc"] = "",
			},
			[54257815] = {
				["title"] = "Innkeeper",
				["level"] = 1,
				["icon"] = 13,
				["desc"] = "",
			},
			[63563234] = {
				["title"] = "Hunters Hall",
				["level"] = 1,
				["icon"] = 18,
				["desc"] = "",
			},
		},
		["Karazhan"] = {
			[43168389] = {
				["icon"] = 1,
				["level"] = 6,
				["title"] = "Urne",
				["desc"] = "Summon Boss Here",
			},
			[83694973] = {
				["icon"] = 8,
				["level"] = 4,
				["title"] = "Maiden of Virtue",
				["desc"] = "Boss",
			},
			[80056898] = {
				["icon"] = 3,
				["level"] = 15,
				["title"] = "Chess Event",
				["desc"] = "",
			},
			[84657219] = {
				["title"] = "Continue to Prince Malchezaar",
				["level"] = 15,
				["icon"] = 3,
				["desc"] = "",
			},
			[69134323] = {
				["icon"] = 3,
				["level"] = 4,
				["title"] = "Back to Mores",
				["desc"] = "",
			},
			[24236096] = {
				["title"] = "Netherspite",
				["level"] = 12,
				["icon"] = 3,
				["desc"] = "",
			},
			[58885438] = {
				["title"] = "Back to Nightbane",
				["level"] = 8,
				["icon"] = 3,
				["desc"] = "",
			},
			[27026352] = {
				["title"] = "Moroes",
				["level"] = 3,
				["icon"] = 8,
				["desc"] = "Boss",
			},
			[60151757] = {
				["icon"] = 3,
				["level"] = 9,
				["title"] = "Back to Nightbane",
				["desc"] = "",
			},
			[62307411] = {
				["icon"] = 3,
				["level"] = 16,
				["title"] = "Continue to Prince Malchezaar",
				["desc"] = "",
			},
			[53966128] = {
				["icon"] = 3,
				["level"] = 7,
				["title"] = "Continue to The Curator",
				["desc"] = "",
			},
			[57815326] = {
				["title"] = "Continue to Netherspite",
				["level"] = 10,
				["icon"] = 3,
				["desc"] = "",
			},
			[32156256] = {
				["icon"] = 3,
				["level"] = 10,
				["title"] = "Back to The Curator",
				["desc"] = "",
			},
			[45195230] = {
				["title"] = "Back to Shade of Aran",
				["level"] = 12,
				["icon"] = 3,
				["desc"] = "",
			},
			[41131412] = {
				["title"] = "Back to The Big Bad Wolf",
				["level"] = 6,
				["icon"] = 3,
				["desc"] = "",
			},
			[66894243] = {
				["title"] = "Back to Maiden of Virtue",
				["level"] = 3,
				["icon"] = 3,
				["desc"] = "",
			},
			[39738333] = {
				["title"] = "Back to Attumen",
				["level"] = 3,
				["icon"] = 3,
				["desc"] = "",
			},
			[62942198] = {
				["title"] = "To Nightbane",
				["level"] = 5,
				["icon"] = 3,
				["desc"] = "",
			},
			[52039063] = {
				["icon"] = 3,
				["level"] = 17,
				["title"] = "Back to",
				["desc"] = "",
			},
			[27015823] = {
				["title"] = "Skip to Chess Event",
				["level"] = 12,
				["icon"] = 3,
				["desc"] = "",
			},
			[79096032] = {
				["title"] = "Continue to Prince Malchezaar",
				["level"] = 14,
				["icon"] = 3,
				["desc"] = "along here",
			},
			[49363674] = {
				["icon"] = 8,
				["level"] = 9,
				["title"] = "The Curator",
				["desc"] = "Boss\nPet: Menagerie Custodian",
			},
			[41341428] = {
				["icon"] = 3,
				["level"] = 14,
				["title"] = "Prinz Malchezaar",
				["desc"] = "along here",
			},
			[36104171] = {
				["title"] = "Netherspite",
				["level"] = 13,
				["icon"] = 8,
				["desc"] = "Boss",
			},
			[43598341] = {
				["icon"] = 3,
				["level"] = 5,
				["title"] = "Back to The Big Bad Wolf",
				["desc"] = "",
			},
			[69576593] = {
				["icon"] = 3,
				["level"] = 7,
				["title"] = "Back to Nightbane",
				["desc"] = "",
			},
			[45308245] = {
				["icon"] = 8,
				["level"] = 1,
				["title"] = "Attumen",
				["desc"] = "Boss\nMount: Fiery Warhorse",
			},
			[64876930] = {
				["icon"] = 3,
				["level"] = 6,
				["title"] = "Continue to The Curator",
				["desc"] = "",
			},
			[52886360] = {
				["icon"] = 3,
				["level"] = 1,
				["title"] = "Continue to Moroes",
				["desc"] = "",
			},
			[36116192] = {
				["title"] = "Chess Event",
				["level"] = 14,
				["icon"] = 8,
				["desc"] = "Boss",
			},
			[66472423] = {
				["title"] = "Shade of Aran",
				["level"] = 11,
				["icon"] = 3,
				["desc"] = "",
			},
			[53967924] = {
				["icon"] = 3,
				["level"] = 13,
				["title"] = "Back to Shade of Aran",
				["desc"] = "",
			},
			[36422198] = {
				["icon"] = 3,
				["level"] = 10,
				["title"] = "Continue to Terestian Illhoof",
				["desc"] = "hierlang",
			},
			[51513128] = {
				["title"] = "Prinz Malchezaar",
				["level"] = 17,
				["icon"] = 8,
				["desc"] = "Boss\nPet: Netherspace Abyssal",
			},
			[52256994] = {
				["icon"] = 8,
				["level"] = 11,
				["title"] = "Terestian illhoof",
				["desc"] = "Boss\nPet: Fiendish Imp",
			},
			[46909175] = {
				["title"] = "Nightbane",
				["level"] = 6,
				["icon"] = 8,
				["desc"] = "Boss",
			},
			[71712599] = {
				["icon"] = 8,
				["level"] = 10,
				["title"] = "Shade of Aran",
				["desc"] = "Boss",
			},
			[17823449] = {
				["icon"] = 8,
				["level"] = 4,
				["title"] = "The Big Bad Wolf",
				["desc"] = "Boss\nPet: Lil' Bad Wolf",
			},
			[70967202] = {
				["icon"] = 3,
				["level"] = 16,
				["title"] = "Back to Chess Event",
				["desc"] = "",
			},
			[39631749] = {
				["title"] = "Back to Chess Event",
				["level"] = 12,
				["icon"] = 3,
				["desc"] = "",
			},
			[54175021] = {
				["icon"] = 3,
				["level"] = 8,
				["title"] = "Continue to The Curator",
				["desc"] = "",
			},
			[27322286] = {
				["title"] = "The Big Bad Wolf",
				["level"] = 4,
				["icon"] = 3,
				["desc"] = "",
			},
			[30126417] = {
				["icon"] = 3,
				["level"] = 9,
				["title"] = "Shade of Aran & Terestian Illhoof",
				["desc"] = "along here",
			},
			[19944179] = {
				["icon"] = 3,
				["level"] = 4,
				["title"] = "Next to Nightbane",
				["desc"] = "",
			},
		},
		["CavernofLostSpirits"] = {
			[53205671] = {
				["icon"] = 3,
				["title"] = "Zarhym",
				["desc"] = "Rare Mob",
			},
			[53943121] = {
				["icon"] = 3,
				["title"] = "Zarhyms body",
				["desc"] = "",
			},
			[45893191] = {
				["title"] = "Rock Moss",
				["icon"] = 8,
				["desc"] = "Rare Mob",
			},
		},
		["HowlingFjord"] = {
			[28393345] = {
				["icon"] = 16,
				["title"] = "Beegle Blastfuse <Master Pet Tamer>",
				["desc"] = "Pet-Trainer\nFlying, water, Flying",
			},
			[68386761] = {
				["icon"] = 4,
				["title"] = "Val'kyr Pet",
				["desc"] = "",
			},
			[72444307] = {
				["title"] = "Val'kyr Pet",
				["icon"] = 4,
				["desc"] = "",
			},
			[45604308] = {
				["title"] = "Val'kyr Pet",
				["icon"] = 4,
				["desc"] = "",
			},
		},
		["DreadWastes"] = {
			[27461704] = {
				["title"] = "Elite shell Quest [16mile hp]",
				["icon"] = 3,
				["desc"] = "= Quest for [Gokk'lok's Shell]\nUnderwater 27.4, 16.2",
			},
			[73342168] = {
				["title"] = "Krol the Blade",
				["icon"] = 8,
				["desc"] = "Rare Mob\nDrops 300% EP Flask",
			},
			[36933187] = {
				["title"] = "Gar'lok",
				["icon"] = 8,
				["desc"] = "Rare Mob Spawn 1\nhidden in the hut",
			},
			[36766270] = {
				["title"] = "Omnis Grinlok",
				["icon"] = 8,
				["desc"] = "Rare Mob - Runs here\nDrops golden Fleece (extra Gold Trinket)",
			},
			[71593710] = {
				["title"] = "Karr the Darkener",
				["icon"] = 8,
				["desc"] = "Rare Mob\nDrops Pet",
			},
			[47903034] = {
				["icon"] = 4,
				["title"] = "Malik's Stalwart Spear",
				["desc"] = "= Agi Polearm 450 lvl 86\nInserted between the stone and the Black Tree",
			},
			[55056401] = {
				["title"] = "Ik-Ik the Nimble",
				["icon"] = 8,
				["desc"] = "Rare Mob\nIn a cave",
			},
			[41446344] = {
				["title"] = "Manipulator's Talisman",
				["icon"] = 4,
				["desc"] = "= Trinket DMG 450 lvl 86\nNPC-Scan: 65552\n",
			},
			[24392743] = {
				["title"] = "Dak the Breaker",
				["icon"] = 8,
				["desc"] = "Rare Mob",
			},
			[35372194] = {
				["title"] = "Ai-Li Skymirror",
				["icon"] = 8,
				["desc"] = "Rare Mob",
			},
			[71563682] = {
				["icon"] = 4,
				["title"] = "Wind-Reaver's Dagger of Quick Strikes",
				["desc"] = "= Agi dagger 450 lvl 86\nhidden in purple bush 71.8, 36.1",
			},
			[76022049] = {
				["title"] = "Gate of the Setting Sun",
				["icon"] = 28,
				["desc"] = "Instance Entrance",
			},
			[28184313] = {
				["title"] = "Blade of the Poisoned Mind",
				["icon"] = 4,
				["desc"] = "= 1h Sword Intelligence 450 lvl 86\nIn the bushes next to the Cave Entrance",
			},
			[39024128] = {
				["title"] = "Gar'lok",
				["icon"] = 1,
				["desc"] = "Rare Mob Spawn 2",
			},
			[53653240] = {
				["title"] = "Dailys",
				["icon"] = 6,
				["desc"] = "Klaxxi Dailys",
			},
			[55847799] = {
				["title"] = "Swarming Cleaver of Ka'roz",
				["icon"] = 4,
				["desc"] = "= 2h Sword 450 lvl 86\n56.8, 77.6 Between two stones in the coral\n",
			},
			[64105904] = {
				["title"] = "Nalash Verdantis",
				["icon"] = 8,
				["desc"] = "Rare Mob\nDrops Pet",
			},
			[29899189] = {
				["title"] = "Dissector's Staff of Mutation",
				["icon"] = 4,
				["desc"] = "= Intelligence Staff 450 lvl 86\nOn the platform below the stone column 30.2 90.8",
			},
			[65826387] = {
				["title"] = "Blade of the Prime",
				["icon"] = 4,
				["desc"] = "In the cave - Stuck in a root behind the Elite Mob",
			},
			[61228740] = {
				["title"] = "Burning Pandaren Spirit <Grand Master Pet Tamer>",
				["cont"] = 1,
				["icon"] = 16,
				["desc"] = "Pet-Trainer\nAquatic, Critter, Elemental",
			},
			[25755489] = {
				["title"] = "Bloodsoaked Chitin Fragment",
				["icon"] = 4,
				["desc"] = "=Trinket Mastery+Agi 450 lvl 86\nUnderwater in the cave",
			},
			[31882944] = {
				["title"] = "Lucid Amulet of the Agile Mind",
				["icon"] = 4,
				["desc"] = "= neck Intelligenz 450 lvl 86\nLying on stone next to Schwazem tree 32,30",
			},
			[38923462] = {
				["title"] = "Heart of Fear",
				["icon"] = 28,
				["desc"] = "Entrance 10/25 Raid",
			},
			[47125985] = {
				["title"] = "Zandalari Warbringer & Warscout",
				["cont"] = 1,
				["icon"] = 8,
				["desc"] = "5.2 Rare Mob - Drops Mount\nJade, Slate, Amber, or Golden Primordial Direhorn\nNPC-Scan id: 69769 & 69768",
			},
			[53525639] = {
				["title"] = "Swarmkeeper's Medallion",
				["icon"] = 4,
				["desc"] = "= Trinket: +Crit +Haste ilvl: 450 lvl: 86\nOn the ground Nearby the stone\nat 54.3, 56.5",
			},
			[54943741] = {
				["title"] = "Wastewalker Shu <Grand Master Pet Tamer>",
				["icon"] = 16,
				["desc"] = "Pet-Trainer\nAquatic, Elemental, Wildlife",
			},
		},
		["Krasarang_terrain1"] = {
			[41859219] = {
				["title"] = "Equipment Locker",
				["icon"] = 4,
				["desc"] = "Random BoP Boots 419 lvl 86\nvery bottom of the ship\nCounts as treasure for Lost and Found!",
			},
			[30463829] = {
				["title"] = "Cournith Waterstrithe",
				["icon"] = 8,
				["desc"] = "Rare Mob\nEpic Pants 440",
			},
			[15403638] = {
				["title"] = "Torik-Ethis",
				["icon"] = 8,
				["desc"] = "Rare Mob\nEpic Plate Tank Pants 440",
			},
			[66972312] = {
				["title"] = "Qu'nas",
				["icon"] = 8,
				["desc"] = "Epic Strength Plate Pants",
			},
			[52348787] = {
				["title"] = "Spriggin",
				["icon"] = 8,
				["desc"] = "Rare Mob\nEpic Will Leather Pants 440",
			},
			[56334652] = {
				["title"] = "Arness the Scale",
				["icon"] = 8,
				["desc"] = "Rare Mob\nEpic Mail Heal Pants 440",
			},
			[84962696] = {
				["title"] = "Dalan Nightbreaker",
				["icon"] = 24,
				["desc"] = "250 Honor\nEpic PvP Resilience Trinket\nNPC-Scan: 68318",
			},
			[32966448] = {
				["title"] = "Dailys",
				["icon"] = 6,
				["desc"] = "Respectful with Lotus: \nThe Celestial Exalted",
			},
			[50634883] = {
				["title"] = "Pandaren Fishing Spear",
				["icon"] = 4,
				["desc"] = "Agility Polearm 419 lvl 86\nStuck in the ground behind Uncle Deming",
			},
			[83853087] = {
				["title"] = "Mavis Harms",
				["icon"] = 24,
				["desc"] = "250 Honor\nEpic Pvp-power Trinket\nNPC-Scan: 68317",
			},
			[10505714] = {
				["icon"] = 25,
				["title"] = "Muerta",
				["desc"] = "250 Honor\nEpic insignia 1 min CD\nNPC-Scan: 68322",
			},
			[85922431] = {
				["title"] = "Dalies (Alliance)",
				["icon"] = 6,
				["desc"] = "Operation Shieldwall",
			},
			[71020859] = {
				["title"] = "Saurok Stone Tablet",
				["icon"] = 4,
				["desc"] = "100g Grey Item\nIn the cave",
			},
			[15135666] = {
				["icon"] = 25,
				["title"] = "Kar Warmaker",
				["desc"] = "250 Honor\nEpic Resiliences Trinket \nNPC-Scan: 68322\n",
			},
			[53088851] = {
				["title"] = "Recipe: Banana Infused Rum",
				["icon"] = 4,
				["desc"] = "Up on the ship in a barrel\nCounts as treasure!",
			},
			[87412895] = {
				["title"] = "Disha Fearwarden",
				["icon"] = 24,
				["desc"] = "250 Honor\nNPC-Scan: 68319",
			},
			[38986616] = {
				["title"] = "Zandalari Warbringer & Warscout",
				["cont"] = 1,
				["icon"] = 8,
				["desc"] = "5.2 Rare Mob - Drops Mount\nJade, Slate, Amber, or Golden Prinordial Direhorn\nNPC-Scan id: 69769 & 69768",
			},
			[53773550] = {
				["title"] = "Gaarn the Toxic",
				["icon"] = 8,
				["desc"] = "Rare Mob\nEpic Cloth Will Pants 440",
			},
			[67454428] = {
				["title"] = "Dailys",
				["icon"] = 6,
				["desc"] = "Angler quests",
			},
			[52077247] = {
				["title"] = "Stack of Papers",
				["icon"] = 4,
				["desc"] = "Grey Item 15g\nLocated next to the hatch\nNo treasure!",
			},
			[39032911] = {
				["title"] = "Go-Kan",
				["icon"] = 8,
				["desc"] = "Rare Mob\nEpic Mail Aggi Pants 440",
			},
			[40475514] = {
				["title"] = "Ruun Ghostpaw",
				["icon"] = 8,
				["desc"] = "Rare Mob\nPanda in the 2. floor\nEpic Aggi Leather Pants 440",
			},
			[12075660] = {
				["icon"] = 6,
				["title"] = "Dailys (Horde)",
				["desc"] = "Dominance Offensive",
			},
			[11306632] = {
				["icon"] = 25,
				["title"] = "Ubunti the Shade",
				["desc"] = "250 Honor\nEpic PvP power Trinket\nNPC-Scan: 68320",
			},
			[62014675] = {
				["icon"] = 16,
				["title"] = "Mo'ruk",
				["desc"] = "Pet-Trainer\nWildlife, Flying (Moth), Aquatic",
			},
		},
		["SholazarBasin"] = {
			[44216890] = {
				["icon"] = 4,
				["title"] = "Val'kyr Pet",
				["desc"] = "",
			},
			[36951933] = {
				["icon"] = 4,
				["title"] = "Val'kyr Pet",
				["desc"] = "",
			},
			[58332222] = {
				["icon"] = 4,
				["title"] = "Val'kyr Pet",
				["desc"] = "",
			},
		},
		["ValeofEternalBlossoms"] = {
			[79783344] = {
				["title"] = "Daily",
				["icon"] = 6,
				["desc"] = "Archaeology",
			},
			[43904389] = {
				["icon"] = 6,
				["title"] = "Dailys",
				["desc"] = "Lotus",
			},
			[46646014] = {
				["icon"] = 2,
				["title"] = "Cracklefang",
				["desc"] = "cooking Rare Mob",
			},
			[29109039] = {
				["icon"] = 8,
				["title"] = "Major Nanners",
				["desc"] = "Rare Mob\nHelpful Wikky's Whistle",
			},
			[46966415] = {
				["icon"] = 2,
				["title"] = "Spirit of Lao-Fe <The Slavebinder>",
				["desc"] = "cooking Rare Mob",
			},
			[67201404] = {
				["icon"] = 16,
				["title"] = "Burning Panderan Spirit",
				["desc"] = "",
			},
			[25902452] = {
				["title"] = "Key exchange in the halls",
				["icon"] = 4,
				["desc"] = "against Lotus reputation",
			},
			[41646949] = {
				["icon"] = 8,
				["title"] = "Ai-Ran the Shifting Cloud",
				["desc"] = "Rare Mob\nin the cave",
			},
			[57494232] = {
				["icon"] = 6,
				["title"] = "Dailys",
				["desc"] = "Lotus",
			},
			[78793486] = {
				["title"] = "Mogu'shan Palace",
				["icon"] = 28,
				["desc"] = "Instance Entrance (87-89 / 90 Heroic)",
			},
			[36265067] = {
				["icon"] = 2,
				["title"] = "Vicejaw",
				["desc"] = "cooking Rare Mob",
			},
			[68683096] = {
				["icon"] = 8,
				["title"] = "Sahn Tidehunter",
				["desc"] = "Rare Mob\nDrops +50% swim speed",
			},
			[67564093] = {
				["title"] = "Aki the Chosen <Grand Master Pet Tamer>",
				["icon"] = 16,
				["desc"] = "Pet-Trainer\nCritter, Dragonkin, Aquatic",
			},
			[15887302] = {
				["title"] = "Gate of the Setting Sun",
				["icon"] = 28,
				["desc"] = "Instance Entrance",
			},
			[43205147] = {
				["icon"] = 1,
				["title"] = "Moldo One-Eye",
				["desc"] = "",
			},
			[8033367] = {
				["icon"] = 2,
				["title"] = "Vyraxxis <Krik'thik Swarm-Lord>",
				["desc"] = "cooking Rare Mob",
			},
			[73374227] = {
				["icon"] = 3,
				["title"] = "Lotus",
				["desc"] = "",
			},
			[24391394] = {
				["icon"] = 2,
				["title"] = "Huo-Shuang <Shao-Tien Imperion>",
				["desc"] = "cooking Rare Mob\nIn Gou-Lai halls",
			},
			[30497874] = {
				["icon"] = 2,
				["title"] = "Shadowmaster Sydow <The Soul-Gatherer>",
				["desc"] = "cooking Rare Mob",
			},
			[34988997] = {
				["icon"] = 2,
				["title"] = "Aetha",
				["desc"] = "cooking Rare Mob",
			},
			[65893976] = {
				["icon"] = 2,
				["title"] = "Quid <Spirit of the Misty Falls>",
				["desc"] = "cooking Rare Mob",
			},
			[61142430] = {
				["icon"] = 6,
				["title"] = "Horde Daily+Weekly",
				["desc"] = "",
			},
			[39072529] = {
				["title"] = "Urgolax",
				["icon"] = 8,
				["desc"] = "Rare Mob\nSpecial Drop: Chalice of Secrets (Funitem)",
			},
			[17024795] = {
				["icon"] = 2,
				["title"] = "Bai-Jin the Butcher <Shao-Tien Imperion>",
				["desc"] = "cooking Rare Mob",
			},
			[87624337] = {
				["icon"] = 8,
				["title"] = "Yorik Sharpeye",
				["desc"] = "Rare Mob",
			},
			[6645885] = {
				["icon"] = 2,
				["title"] = "Kri'chon <The Corpse-Reaver>",
				["desc"] = "cooking Rare Mob",
			},
			[27395661] = {
				["icon"] = 2,
				["title"] = "General Temuja <The Soul-Slaver>",
				["desc"] = "cooking Rare Mob",
			},
			[27714169] = {
				["icon"] = 2,
				["title"] = "Baolai the Immolator <Shao-Tien Imperion>",
				["desc"] = "cooking Rare Mob",
			},
			[14813344] = {
				["icon"] = 8,
				["title"] = "Kang the Soul Thief",
				["desc"] = "Rare Mob\nSpecial Drop: Kang's Bindstone (Funitem)",
			},
			[14125852] = {
				["title"] = "Kal'tik the Veröthe",
				["icon"] = 8,
				["desc"] = "Rare Mob",
			},
			[26751330] = {
				["icon"] = 2,
				["title"] = "Gochao the Ironfist <Shao-Tien Imperion>",
				["desc"] = "cooking Rare Mob",
			},
			[25681603] = {
				["icon"] = 2,
				["title"] = "Bloodtip <Ashweb Matriarch>",
				["desc"] = "cooking Rare Mob\nIn Gou-Lai halls\n(Spider in ritual chamber)",
			},
			[45257666] = {
				["icon"] = 2,
				["title"] = "Wulon",
				["desc"] = "cooking Rare Mob",
			},
			[33976192] = {
				["icon"] = 8,
				["title"] = "Moldo One-Eye",
				["desc"] = "Rare Mob\non the banks of the river up direction Lake",
			},
			[83925959] = {
				["icon"] = 6,
				["title"] = "Alliance Daily+Weekly",
				["desc"] = "",
			},
		},
	}	

		
for k,v in pairs(aegerUI_HandyNotes_Install) do
		HandyNotes_HandyNotesDB.global[k] = v
	end
end